Support ProjectionExpression
44103/awschains pull request #10
Opened 2023-05-21 03:43 UTC by yahoooooo4624

2023-05-21 03:46 UTC, yahoooooo4624 commented
確認お願いします。

2023-05-21 03:51 UTC, yahoooooo4624 commented on conditions.py
> +    def _add_pelist_to_atts(self):
この関数名は、add_expression_attribute_names()とかの方が良いか

2023-05-21 03:53 UTC, yahoooooo4624 commented on conditions.py
> +    def _convert_pelist_to_pe(self):
この関数名は、use_expression_attribute_names()とかの方が良いか

2023-05-21 08:49 UTC, 44103 commented
[nit]
`attribute`は`attr`と略されることが多いので、よければそちらに変更してもらえればと。
https://e-words.jp/w/%E3%82%A2%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%83%88.html

2023-05-21 09:29 UTC, yahoooooo4624 commented
> [nit] `attribute`は`attr`と略されることが多いので、よければそちらに変更してもらえればと。 https://e-words.jp/w/%E3%82%A2%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%83%88.html

指摘ありがとう。修正しました。
get_item()のマージが完了したらrebaseするので連絡ください。

2023-05-21 11:32 UTC, 44103 requested changes
@yahoooooo4624 
遅くなってすみません。
確認お願いします。

2023-05-21 11:32 UTC, 44103 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
[must]
ここのコードは2点の観点から修正の必要があります。
1. DynamoDBのキー名にはスペースも使用できるので、L37のように`self._query["ProjectionExpression"].replace(" ", "")`としてしまうと、キー名の中にあるスペースも消してしまいます。
2. `string.replace()`メソッドは自分自身を書き換えないので、実質L37は働いてません。
   ```python
   >>> s = "a, b"
   >>> s.replace(" ", "")
   'a,b'
   >>> s
   'a, b' 
   ```
おそらく以下のような修正が必要です。
```python
self._pe_list = [key.strip() for key in self._query["ProjectionExpression"].split(",")]
```

2023-05-21 11:32 UTC, 44103 commented on conditions.py
> +        if type(self._query["ProjectionExpression"]) != str:
[nit]
型の比較は`type(...) is not str`の方がいいかもしれないです。

2023-05-21 11:32 UTC, 44103 commented on conditions.py
> +        self._query["FilterExpression"] = bce.condition_expression
[nit]
L16-18とL24-26は同じ処理が入っているので、共通化してもいいですね。

2023-05-21 11:32 UTC, 44103 commented on conditions.py
> +        self._query["ProjectionExpression"] = ",".join(self._pe_list)
[must]
L47で`self._pe_list`の中身が書き換わって役割が変わってしまってるので、一時変数を作ったほうが良いと思います。
```python
pe_name_list = [reversed_attr_names[pe] for pe in self._pe_list]
self._query["ProjectionExpression"] = ",".join(pe_name_list)
```

2023-05-21 14:06 UTC, yahoooooo4624 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
指摘ありがとう。キー名にスペースを含められるのは知りませんでした。
指摘通り、split()してからstrip()に変更します。

2023-05-21 14:51 UTC, yahoooooo4624 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
少し考えたんですが、keyの両端にスペースを含んでいた場合は対応できません。

2023-05-21 14:53 UTC, yahoooooo4624 commented on conditions.py
> +        if type(self._query["ProjectionExpression"]) != str:
シングルトンの比較なので、指摘の通り、isでの比較で良いと考えます。

2023-05-21 15:16 UTC, yahoooooo4624 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
以下のような修正案があると思います。
projection()で指定する場合に、
1. str型で、余計なスペースを許可しない
2. str型のリストとする

2023-05-21 15:24 UTC, yahoooooo4624 commented on conditions.py
> +        self._query["FilterExpression"] = bce.condition_expression
共通化します。

2023-05-21 15:29 UTC, yahoooooo4624 commented on conditions.py
> +        self._query["ProjectionExpression"] = ",".join(self._pe_list)
「ProjectionExpressionリスト」という役割に変化はないと思っていますが、「ExpressionAttributeNamesを使用したProjectionExpressionリスト」という命名に変えたいという意図ですか？

2023-05-21 15:39 UTC, yahoooooo4624 commented on conditions.py
> +        self._query["FilterExpression"] = bce.condition_expression
修正しましたので、ご確認ください。

2023-05-21 15:39 UTC, yahoooooo4624 commented on conditions.py
> +        if type(self._query["ProjectionExpression"]) != str:
修正しましたので、ご確認ください。

2023-05-21 16:13 UTC, yahoooooo4624 commented
rebaseしたら時系列がわかりにくくなってしまいました。
以下のコミット以降が、修正コミットおよびget()メソッド対応の新しいコミットです。
ご確認ください。
[Functionalized common processes](https://github.com/44103/awschains/pull/10/commits/d76b88f0cacc45dda107703daa9d16fed4a9014f)

2023-05-21 21:01 UTC, 44103 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
> 少し考えたんですが、keyの両端にスペースを含んでいた場合は対応できません。
![image](https://github.com/44103/awschains/assets/20487218/c3d87816-62c5-4da4-ab34-e08e850871e2)
確かに、キー名の前後にもスペースが入れられるようですね。クエリするときにクォーテーションなどで囲ってくれればできそうですが。

2023-05-21 21:24 UTC, 44103 commented on conditions.py
> +        self._query["ProjectionExpression"] = ",".join(self._pe_list)
現状のロジックでは、`self._pe_list`が`_add_attr_names_from_pe`や`_use_attr_names_for_pe`メソッドの開始時点では、
```
['ForumName', ' Subject', ' Message', 'LastPostedBy', ' LastPostedDateTime', 'Views']
````
のような値が入っていますが、
`_use_attr_names_for_pe`メソッドの実行後は
```
['#n0', '#n4', '#n5', '#n2', '#n6', '#n3']
```
のような値に変わってしまいます。
`self._pe_list`を次回使う度に、どちらの形式で保存されているのかわからないと、コードが難読化します。

-----

ProjectionExpressionにしか影響せず、状態を保持する必要のない変数なのであれば、そもそもメンバ変数にしないという選択肢もありますね。

2023-05-22 03:30 UTC, yahoooooo4624 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
一旦、str型のリストで指定する方法で実装してみます。

2023-05-22 04:22 UTC, yahoooooo4624 commented on conditions.py
> +        self._query["ProjectionExpression"] = ",".join(self._pe_list)
メンバ変数にしない方向で修正したいと思います。

2023-05-22 09:07 UTC, 44103 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
2文字しか短くならないですが、可変長引数にしてしまうのもいいなと思いました。

2023-05-22 12:47 UTC, yahoooooo4624 commented on conditions.py
> +        self._pe_list = self._query["ProjectionExpression"].split(",")
boto3では、前後に空白を含む属性に対して、ProjectionExpressionで指定して取得することはできない仕様（文字列で指定する都合上、前後の空白は削除される模様）なので、今回は文字列で指定する仕様とします。
また前後の空白はboto3で削除されるようなので、こちらの空白削除処理も行わないこととします。

2023-05-22 13:03 UTC, yahoooooo4624 commented
修正コミットを追加しましたので、ご確認ください。

2023-05-23 09:08 UTC, 44103 approved these changes
いいと思います！
ありがとうございます。
close #3

2023-05-23 09:08 UTC, merged